# See: ../../architecture/architecture_v1.md
import json
import logging
import re
import sys
from pathlib import Path

import anthropic
import jsonschema
from dotenv import load_dotenv

_SCHEMA_PATH = Path(__file__).parent.parent / "schemas" / "03_llm_chunked.v1.json"

load_dotenv()

_SYSTEM = """\
You are an expert requirements document parser.

Your task: given a numbered requirements specification document, identify its structure and output ONLY valid JSON.

OUTPUT RULES (strictly enforced):
- Output ONLY the JSON object. No markdown fences, no explanation.
- Never copy document text into the output, EXCEPT for "title" in sections.
- All locations use {{"page": N, "line_start": M, "line_end": K}} where N is the page number and line numbers are 1-based within that page. line_end is inclusive.
- gen_section_number: assign sequentially in document order — "GS001", "GS002", etc. Prefix G = generated by pipeline, not from the document.
- parent_gen_section_number: the gen_section_number of the immediately enclosing heading. null if top-level.
- skip_pages: page numbers that are purely navigational (cover page, table of contents, revision history, index). Emit no sections or spec_items from these pages.

HEADING DETECTION:
{heading_instruction}

SPEC ITEM DETECTION:
{item_instruction}

For each spec item:
- item_id: verbatim ID if one exists, null if the document has no formal IDs.
- item_type / classification: infer ONLY from an explicit attribute label in the text or an unambiguous ID prefix. null in all other cases.
- source: "inline" (prose paragraph), "list" (bulleted or numbered list entry), "table" (table row — flag as possible_table_noise), "other".
- extra_attrs: only if the item text contains explicit sub-field labels (e.g. "Rationale:", "Note:", "Verification:"). Keys are snake_case of the label, values are loc. Do not invent.
- flags: use "ambiguous_boundary" if unsure where the item ends; "possible_table_noise" if from a table.

OUTPUT SHAPE:
{{
  "source_ref": "<verbatim from input header>",
  "skip_pages": [],
  "sections": [
    {{
      "gen_section_number": "GS001",
      "section_number": "1.2" or null,
      "item_id": null,
      "title": "<verbatim heading text>",
      "parent_gen_section_number": null,
      "loc": {{"page": 1, "line_start": 3, "line_end": 3}}
    }}
  ],
  "spec_items": [
    {{
      "item_id": "REQ-001" or null,
      "item_type": null,
      "classification": null,
      "source": "inline",
      "parent_gen_section_number": "GS001" or null,
      "loc": {{"page": 1, "line_start": 5, "line_end": 8}},
      "extra_attrs": {{}},
      "flags": []
    }}
  ]
}}"""


def _heading_instruction(heading_pattern: str | None) -> str:
    if heading_pattern:
        return (
            f"A heading line matches this regex: {heading_pattern}\n"
            "Emit a section entry for each line that matches. Do not emit sections for non-matching lines."
        )
    return (
        "No heading pattern was detected in this document. Identify headings semantically:\n"
        "- Short line (typically ≤ 60 characters)\n"
        "- Title case, sentence case, or ALL CAPS\n"
        "- No sentence-ending punctuation (does not end with a period)\n"
        "- Does not end with a colon (those are attribute labels)\n"
        "- Followed by body text or spec items, not by another short line of the same style\n"
        "When uncertain, prefer not emitting a section over emitting a false one."
    )


def _item_instruction(item_id_pattern: str | None) -> str:
    if item_id_pattern:
        return (
            f"Spec items have IDs matching this regex: {item_id_pattern}\n"
            "Each item starts at the line containing its ID and ends at the line immediately before the next item ID or heading."
        )
    return (
        "This is a raw specification — no formal requirement IDs exist.\n"
        "Identify spec items as contiguous blocks of text that express a distinct engineering statement:\n"
        "- A system capability or behavior (look for 'shall', 'must', 'will', 'should')\n"
        "- A constraint, assumption, or interface definition\n"
        "Each item must be a single logical statement. Do not split a sentence across items. "
        "Do not merge statements that address different topics. Set item_id to null for all items."
    )


def _format_pages(pages: list[dict]) -> str:
    """Render pages as numbered lines for the LLM prompt."""
    parts = []
    for p in pages:
        lines = p["text"].split("\n")
        numbered = "\n".join(f"L{i + 1}: {line}" for i, line in enumerate(lines))
        parts.append(f"=== PAGE {p['page']} ===\n{numbered}")
    return "\n\n".join(parts)


def run_chunker(normalized: dict) -> dict:
    normalization = normalized.get("normalization", {})
    pages = normalized["pages"]
    source_ref = normalized["source_ref"]

    item_id_pattern = normalization.get("item_id_pattern")
    heading_pattern = normalization.get("heading_pattern")

    system_prompt = _SYSTEM.format(
        heading_instruction=_heading_instruction(heading_pattern),
        item_instruction=_item_instruction(item_id_pattern),
    )
    document_text = _format_pages(pages)
    user_message = f"SOURCE_REF: {source_ref}\n\n{document_text}"

    client = anthropic.Anthropic()
    message = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=8192,
        system=system_prompt,
        messages=[{"role": "user", "content": user_message}],
    )
    raw_response = message.content[0].text.strip()
    cleaned = re.sub(r"```json\s*([\s\S]*?)\s*```", r"\1", raw_response).strip()

    try:
        result = json.loads(cleaned)
    except json.JSONDecodeError as exc:
        raise ValueError(f"LLM returned unparseable JSON: {exc}\nRaw response: {raw_response[:500]}") from exc

    result["source_ref"] = source_ref  # enforce regardless of what the LLM produced
    return result


def save_result(input_path: Path) -> Path:
    input_path = input_path.resolve()
    if not input_path.exists():
        raise FileNotFoundError(f"Input not found: {input_path}")
    with open(input_path, encoding="utf-8") as f:
        normalized = json.load(f)
    result = run_chunker(normalized)
    schema = json.loads(_SCHEMA_PATH.read_text(encoding="utf-8"))
    try:
        jsonschema.validate(result, schema)
    except jsonschema.ValidationError as exc:
        raise ValueError(f"Chunker output failed schema validation: {exc.message}") from exc
    stem = input_path.stem.removeprefix("01_normalized_")
    output_path = input_path.parent / f"03_llm_chunked_{stem}.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)
    return output_path


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    if len(sys.argv) < 2:
        logging.error("Usage: python S3_llm_chunker.py <path_to_normalized.json>")
        sys.exit(1)
    try:
        out = save_result(Path(sys.argv[1]))
        with open(out, encoding="utf-8") as f:
            data = json.load(f)
        logging.info(f"Saved to {out}")
        logging.info(
            f"Chunked: {len(data['sections'])} sections, "
            f"{len(data['spec_items'])} spec items, "
            f"skip_pages={data.get('skip_pages', [])}"
        )
    except (FileNotFoundError, ValueError) as e:
        logging.error(e)
        sys.exit(1)
